version: '2'
services: 
	mysql: 
    	image: mysql
    	volumes:
    		- '$PWD/conf/mysql:/etc/mysql'
    	ports: 
    		- '3306:3306'
			environment: 
      	- MYSQL_ROOT_PASSWORD=16051223
    	container_name: mysql_exp
	redis: 
		image: redis
		ports:
			- '6379:6379'
		container_name: redis_exp